import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, GitFork as Github, Mail } from "lucide-react";
import { Breadcrumbs } from "@/components/marketing/breadcrumbs";
import { MarketingFooter } from "@/components/marketing/footer";
import { JsonLdScript } from "@/components/marketing/json-ld";
import { MarketingButton } from "@/components/marketing/marketing-button";
import { SITE_CONTENT_UPDATED, breadcrumbJsonLd, jsonLdGraph, marketingMetadata, webPageJsonLd } from "@/lib/seo";

export const metadata: Metadata = marketingMetadata({
  title: "About Raltic: Accountable AI Agent Workflows",
  description: "Raltic builds shared workflow rooms where people coordinate local and cloud AI agents, inspect evidence, review work, and retain decisions.",
  path: "/about",
  keywords: ["about Raltic", "AI agent workflow company", "agent orchestration platform"],
});

export default function AboutPage() {
  return (
    <>
      <JsonLdScript data={jsonLdGraph([webPageJsonLd({ path: "/about", name: "About Raltic", description: metadata.description as string, dateModified: SITE_CONTENT_UPDATED }), breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "About", path: "/about" }])])} />
      <section className="border-b border-black/[0.07] bg-[#fafaf8] pt-28 pb-20 sm:pt-32"><Breadcrumbs items={[{ name: "Home", href: "/" }, { name: "About", href: "/about" }]} /><div className="mx-auto mt-8 max-w-4xl px-6 text-center"><p className="text-xs font-medium uppercase text-blue-700">About Raltic</p><h1 className="mt-5 text-balance text-5xl font-medium leading-[1.05] text-zinc-900 sm:text-6xl">Agent work should be as reviewable as human work.</h1><p className="mx-auto mt-6 max-w-3xl text-balance text-lg leading-relaxed text-zinc-600">Raltic is building the shared operating layer for teams that use AI agents every day. Local and cloud agents can work in the same workflow rooms, while people retain evidence, task ownership, review, and the final decision.</p></div></section>
      <section className="bg-white px-6 py-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-medium uppercase text-blue-700">Why we exist</p><h2 className="mt-4 text-3xl font-medium text-zinc-900 sm:text-4xl">AI output is abundant. Accountable outcomes are not.</h2><p className="mt-5 text-base leading-8 text-zinc-600">Teams now use several models, coding agents, connected tools, and private chat sessions. The operational problem is no longer access to an answer. It is knowing what was requested, what evidence an agent used, who owns the next task, whether a person reviewed the result, and what the team should remember.</p><p className="mt-4 text-base leading-8 text-zinc-600">Raltic organizes that work around bounded workflow rooms rather than a generic assistant. The product is deliberately honest about runtime, permission, and data boundaries because trust depends on describing what each layer actually controls.</p></div><div className="grid gap-4">{[{t:"Workflow before autonomy",b:"Start with a repeatable process and a reviewable artifact before adding agents or triggers."},{t:"Evidence before confidence",b:"Prefer sources, artifacts, diffs, tests, and explicit gaps over fluent unsupported conclusions."},{t:"Human ownership",b:"Agents prepare and propose. People remain responsible for consequential product, engineering, customer, and business decisions."},{t:"Interoperable runtimes",b:"Use verified Claude Code and Codex bridge runtimes alongside managed cloud agents without forcing one provider model."}].map((item) => <div key={item.t} className="rounded-lg border border-zinc-200 bg-zinc-50 p-5"><h3 className="font-medium text-zinc-900">{item.t}</h3><p className="mt-2 text-sm leading-relaxed text-zinc-600">{item.b}</p></div>)}</div></div></section>
      <section className="border-y border-black/[0.07] bg-[#faf9f6] px-6 py-20"><div className="mx-auto max-w-5xl"><div className="grid gap-10 md:grid-cols-3"><div><p className="text-xs font-medium uppercase text-blue-700">Current product</p><p className="mt-3 text-sm leading-relaxed text-zinc-600">Web workspace, local bridge, desktop beta, cloud agents, tasks, run state, workspace memory, and GitHub, Linear, and Notion connectors.</p></div><div><p className="text-xs font-medium uppercase text-blue-700">Verified runtimes</p><p className="mt-3 text-sm leading-relaxed text-zinc-600">Claude Code and OpenAI Codex. OpenClaw and Hermes remain experimental and are excluded from production-ready claims.</p></div><div><p className="text-xs font-medium uppercase text-blue-700">Research standard</p><p className="mt-3 text-sm leading-relaxed text-zinc-600">Comparison and educational content links to current first-party or standards sources, carries update dates, and states when a competing product is the better fit.</p></div></div><div className="mt-12 flex flex-col gap-3 border-t border-zinc-200 pt-8 sm:flex-row"><a href="https://github.com/Digidai/raltic" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm font-medium text-zinc-800 hover:border-zinc-500"><Github className="h-4 w-4" aria-hidden="true" />GitHub repository</a><a href="mailto:hello@raltic.com" className="inline-flex items-center justify-center gap-2 rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm font-medium text-zinc-800 hover:border-zinc-500"><Mail className="h-4 w-4" aria-hidden="true" />hello@raltic.com</a><Link href="/security" className="inline-flex items-center justify-center gap-2 px-4 py-3 text-sm font-medium text-blue-700">Read security boundaries <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div></div></section>
      <MarketingFooter lead={<div className="mx-auto max-w-3xl text-center"><h2 className="text-balance text-3xl font-medium text-zinc-900 sm:text-4xl">Build one accountable workflow with us.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-relaxed text-zinc-600">Raltic is free during private beta.</p><div className="mt-7 flex justify-center"><MarketingButton href="/signup?workflow=launch-readiness" ctaTarget="about_signup">Start free beta <ArrowRight className="h-4 w-4" aria-hidden="true" /></MarketingButton></div></div>} />
    </>
  );
}
