import type { AnswerPage, BlogArticle } from "@/lib/growth-content";
import { EXPANDED_ANSWER_PAGES, EXPANDED_BLOG_ARTICLES } from "@/lib/editorial-content-additions";
import { ROUND_TWO_ANSWER_PAGES, ROUND_TWO_BLOG_ARTICLES } from "@/lib/editorial-content-round-two";

const PUBLISHED = "2026-08-13";

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: "what-is-an-agent-workflow",
    title: "What is an AI agent workflow? A practical operating guide",
    metaTitle: "What Is an AI Agent Workflow? Practical Guide",
    metaDescription: "Learn how AI agent workflows combine a brief, tools, agent execution, human review, and reusable outcomes, with a practical design checklist.",
    keywords: ["AI agent workflow", "agentic workflow", "AI workflow design", "AI agent process"],
    dek: "An agent workflow is not just a longer prompt. It is a repeatable operating process with a defined outcome, bounded tool access, observable execution, and a person who owns the consequential decision.",
    directAnswer: "An AI agent workflow is a repeatable process in which one or more AI agents perform bounded work toward a defined outcome, use approved tools or evidence, expose progress and results for review, and hand the consequential decision to a human owner. A useful workflow includes a brief, execution path, evidence standard, review boundary, and reusable record.",
    published: PUBLISHED,
    updated: PUBLISHED,
    readTime: "9 min read",
    sections: [
      {
        id: "workflow-vs-prompt",
        title: "An agent workflow is an operating system, not a prompt",
        answer: "A prompt requests an output. A workflow defines how work moves from intent to evidence, execution, review, and an accepted result.",
        paragraphs: [
          "A single prompt can be useful for drafting or exploration, but it rarely specifies ownership, tool permissions, failure handling, or what happens after the answer arrives. A workflow turns those missing decisions into an explicit process that another teammate can inspect and repeat.",
          "Anthropic distinguishes predictable workflows from more autonomous agents and recommends choosing the simplest pattern that works. That distinction matters: teams should add autonomy only where it removes real coordination cost without hiding critical decisions.",
        ],
        bullets: ["A bounded objective and named owner", "Inputs and evidence the agent may use", "Tools and permissions required", "Visible progress, output, and uncertainty", "A review point and a reusable outcome"],
      },
      {
        id: "core-components",
        title: "The six components of a production-ready workflow",
        answer: "A durable workflow combines intent, context, execution, controls, evaluation, and memory.",
        paragraphs: [
          "Start by defining the decision or deliverable, not the agent persona. Give the agent only the context and tool access needed for that result. Then decide how the team will observe the run and evaluate the output before it is accepted.",
          "The final component is memory: preserve the brief, evidence, revisions, and decision so the next run starts from the team's actual operating history rather than a fresh chat session.",
        ],
        bullets: ["Intent: what outcome must exist", "Context: what evidence is in scope", "Execution: which agent and tools do the work", "Controls: permissions, stop conditions, and review", "Evaluation: what proves the result is useful", "Memory: what the team retains for the next run"],
      },
      {
        id: "design-first-workflow",
        title: "How to design the first agent workflow",
        answer: "Choose a recurring, bounded process with available evidence and a clear human decision at the end.",
        paragraphs: [
          "Good first workflows are important enough to matter but small enough to review. Launch readiness, research synthesis, customer-risk review, and bounded code review work because the inputs, expected artifact, and decision owner can be named in advance.",
          "Avoid starting with a vague goal such as 'run product operations.' Narrow it to a question, source set, output format, and acceptance criteria. The first trial should prove reviewable value before the team adds more agents or automation triggers.",
        ],
        bullets: ["Pick one process that repeats", "Name the human decision owner", "Define evidence and freshness requirements", "Specify the first useful artifact", "Run manually before automating the trigger"],
      },
      {
        id: "measure-quality",
        title: "Measure the workflow, not the amount of AI output",
        answer: "The right metrics are time to reviewed value, evidence quality, correction rate, and whether the outcome can be reused.",
        paragraphs: [
          "Message volume and token usage are activity metrics. They do not show that an agent helped the team make a better decision. Track how long it takes to reach a reviewable artifact, how often reviewers find unsupported claims, and how much context must be rebuilt on the next run.",
          "A successful workflow creates leverage for both people and future agents: the evidence is inspectable, the approval is explicit, and the accepted result remains available as operating memory.",
        ],
        bullets: ["Time from brief to review-ready output", "Share of claims linked to adequate evidence", "Human correction or rejection rate", "Tasks created and closed from the result", "Context reused in the next run"],
      },
    ],
    sources: [
      { publisher: "Anthropic", label: "Building effective agents", href: "https://www.anthropic.com/engineering/building-effective-agents" },
      { publisher: "OpenAI", label: "A practical guide to building AI agents", href: "https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/" },
      { publisher: "NIST", label: "AI Risk Management Framework", href: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10" },
    ],
    faqs: [
      { q: "What is the difference between an AI workflow and an AI agent?", a: "An agent is a software participant that can reason and act with tools. A workflow is the larger process that defines the objective, context, permissions, handoffs, review, and accepted outcome." },
      { q: "Does an agent workflow need multiple agents?", a: "No. Many useful workflows use one agent and one human reviewer. Add more agents only for a clear specialist task, independent critique, or runtime requirement." },
      { q: "What is a good first agent workflow?", a: "Choose a recurring, bounded decision with available evidence and a named owner, such as launch readiness, research synthesis, customer-risk review, or code review." },
    ],
    related: [{ label: "Workflow rooms", href: "/features/workflow-rooms" }, { label: "Workflow templates", href: "/workflows" }, { label: "What is a workflow room?", href: "/answers/what-is-an-ai-workflow-room" }],
  },
  {
    slug: "human-in-the-loop-ai-workflows",
    title: "Human-in-the-loop AI workflows: where review actually belongs",
    metaTitle: "Human-in-the-Loop AI Workflows: Review Guide",
    metaDescription: "Design human-in-the-loop AI workflows with risk-based review points, useful evidence, clear ownership, and controls that work in practice.",
    keywords: ["human in the loop AI", "AI human oversight", "AI agent review", "human review workflow"],
    dek: "Human-in-the-loop is not a generic checkbox. The reviewer needs authority, evidence, time, and a clearly defined point where an agent proposal becomes an accepted decision.",
    directAnswer: "A human-in-the-loop AI workflow places a qualified person at a meaningful decision point where they can inspect evidence, challenge the agent output, request revision, stop the process, or approve the next action. Effective oversight is risk-based and must give the reviewer real authority rather than asking for a ceremonial click.",
    published: PUBLISHED,
    updated: PUBLISHED,
    readTime: "10 min read",
    sections: [
      { id: "meaningful-review", title: "What makes human review meaningful?", answer: "Review is meaningful only when a person can understand the proposal and change what happens next.", paragraphs: ["A review step fails when the reviewer sees only a confident summary, lacks access to supporting evidence, or is pressured to approve too many low-context outputs. The interface may contain an approval button while the operating process offers no real control.", "NIST's AI RMF treats human roles and oversight as part of governance and risk management. Translate that principle into the workflow by naming the owner, their authority, required evidence, and the action that remains blocked or unaccepted until review."], bullets: ["The reviewer knows what they own", "Evidence and uncertainty are visible", "The reviewer can reject or request changes", "The decision is recorded", "External permissions still enforce sensitive actions"] },
      { id: "risk-based-gates", title: "Place review based on impact and reversibility", answer: "Use more review where actions affect customers, money, access, production systems, or hard-to-reverse decisions.", paragraphs: ["Not every classifier result needs executive approval. Conversely, customer outreach, production changes, legal claims, and access changes should not become automatic just because the agent has performed well on easier tasks.", "Map each step by impact, reversibility, and uncertainty. Let agents automate low-impact preparation while people control high-impact transitions."], bullets: ["Low risk: summarize, classify, or draft", "Medium risk: require evidence review before publishing internally", "High risk: require authorized human action in the destination system", "Unknown risk: pause and gather more context"] },
      { id: "review-packet", title: "Give the reviewer a decision packet", answer: "A reviewer needs the proposal, evidence, uncertainty, affected systems, and acceptance criteria in one place.", paragraphs: ["Do not make the reviewer reconstruct the run from raw logs. The agent should provide a concise recommendation with source links, known gaps, assumptions, and the specific decision requested.", "The workflow room should preserve the packet and reviewer feedback so a revision can be compared against the same criteria."], bullets: ["Proposed action or conclusion", "Supporting and conflicting evidence", "Confidence and known gaps", "Affected users or systems", "Requested decision and owner"] },
      { id: "avoid-rubber-stamping", title: "Prevent review from becoming rubber-stamping", answer: "Keep review volume bounded, sample completed work, and measure corrections rather than approval speed alone.", paragraphs: ["If every trivial step requires approval, reviewers learn to click through. If nothing requires review, the team loses control. Group low-risk work, surface exceptions, and reserve focused attention for consequential transitions.", "Track rejection reasons and repeated corrections. They reveal where the brief, agent tools, or evidence requirements need improvement."], bullets: ["Limit the number of high-attention gates", "Escalate exceptions and uncertainty", "Rotate or separate reviewer roles where appropriate", "Audit a sample of accepted outputs", "Feed common corrections back into the workflow"] },
    ],
    sources: [
      { publisher: "NIST", label: "AI RMF Govern function", href: "https://airc.nist.gov/airmf-resources/airmf/5-sec-core/" },
      { publisher: "Anthropic", label: "Building and evaluating trustworthy agents", href: "https://www.anthropic.com/research/trustworthy-agents" },
      { publisher: "OWASP", label: "Agentic Security Initiative", href: "https://owasp.org/www-project-top-10-for-large-language-model-applications/initiatives/agent_security_initiative/" },
    ],
    faqs: [
      { q: "Does human-in-the-loop mean a person approves every step?", a: "No. Review should match risk. Low-impact preparation can be automated, while consequential, uncertain, or irreversible transitions need focused human control." },
      { q: "Can an approval button guarantee safe AI use?", a: "No. The reviewer also needs evidence, authority, time, and destination-system permissions. A button alone can create false assurance." },
      { q: "What evidence should an agent show before review?", a: "Show the proposed action, supporting and conflicting sources, uncertainty, affected systems, and the exact decision requested." },
    ],
    related: [{ label: "Human review feature", href: "/features/human-review" }, { label: "Approval workflow design", href: "/blog/ai-agent-approval-workflow" }, { label: "How approval gates work", href: "/answers/how-do-ai-agent-approval-gates-work" }],
  },
  {
    slug: "ai-agent-orchestration-guide",
    title: "AI agent orchestration: a practical guide for teams",
    metaTitle: "AI Agent Orchestration Guide for Teams",
    metaDescription: "Learn how to orchestrate AI agents across roles, tools, handoffs, human review, observability, and shared workflow memory.",
    keywords: ["AI agent orchestration", "multi agent orchestration", "agent orchestration platform", "AI agent coordination"],
    dek: "Agent orchestration is the coordination layer that turns separate models and tools into an accountable workflow with clear roles, handoffs, controls, and a human-owned outcome.",
    directAnswer: "AI agent orchestration coordinates which agent performs each task, what context and tools it receives, how agents hand work to one another, how the team observes execution, and where a human reviews the outcome. Good orchestration reduces context loss and permission sprawl; it does not add agents for their own sake.",
    published: PUBLISHED,
    updated: PUBLISHED,
    readTime: "11 min read",
    sections: [
      { id: "orchestration-layer", title: "What an orchestration layer controls", answer: "Orchestration controls routing, context, tool access, state, handoffs, review, and recovery across the workflow.", paragraphs: ["A model call is only one component. Teams also need to determine which runtime receives a task, which evidence follows it, what tools are available, how progress is reported, and what happens when the work is incomplete.", "OpenAI's agent tooling emphasizes handoffs, guardrails, and tracing, while Anthropic recommends composable patterns and the simplest architecture that meets the task. Both point toward explicit workflow design rather than uncontrolled agent proliferation."], bullets: ["Role and task routing", "Context packaging", "Tool and connector grants", "Run and task state", "Handoffs and escalation", "Human review and recovery"] },
      { id: "single-vs-multi", title: "Start with one agent before building a multi-agent system", answer: "Use multiple agents only when specialization or independent critique improves the workflow enough to justify coordination cost.", paragraphs: ["One capable agent with good tools and a clear brief is easier to observe and evaluate. A second agent is useful when it has a genuinely different role, such as source researcher versus critic, or when a separate runtime is required for local repository access.", "Avoid splitting a straightforward task into many personas. Every handoff can lose context, increase latency, and make accountability less clear."], bullets: ["Add a specialist for a distinct evidence domain", "Add a critic for independent challenge", "Add a local runtime for machine-bound tools", "Do not add agents merely to simulate an organization chart"] },
      { id: "shared-state", title: "Use shared workflow state instead of prompt chains", answer: "A shared room, task model, and evidence record make handoffs inspectable and recoverable.", paragraphs: ["Long prompt chains hide where a conclusion came from and make retries brittle. Shared state lets agents and humans read the same brief, claim explicit tasks, post artifacts, and see which work is in review.", "Durable workflow state also supports recovery: a replacement agent or teammate can continue from the recorded context rather than replaying the entire chain."], bullets: ["One source brief", "Attributed updates", "Explicit task ownership", "Artifacts linked to the work", "A recorded final decision"] },
      { id: "production-checklist", title: "Production orchestration checklist", answer: "Validate task fit, permissions, observability, evaluation, fallback, and human ownership before expanding autonomy.", paragraphs: ["Run the workflow manually before adding event triggers. Confirm the agent has only the tools it needs, the reviewer can inspect the evidence, and failures produce an actionable state rather than silence.", "Treat orchestration quality as an operating metric: fewer lost handoffs, better evidence, faster review, and more reusable outcomes."], bullets: ["Bounded objective and owner", "Least-privilege tool access", "Visible run and task state", "Evaluation criteria", "Timeout and escalation path", "Human decision for consequential action"] },
    ],
    sources: [
      { publisher: "OpenAI", label: "The next evolution of the Agents SDK", href: "https://openai.com/index/the-next-evolution-of-the-agents-sdk/" },
      { publisher: "OpenAI", label: "New tools for building agents", href: "https://openai.com/index/new-tools-for-building-agents/" },
      { publisher: "Anthropic", label: "Building effective agents", href: "https://www.anthropic.com/engineering/building-effective-agents" },
    ],
    faqs: [
      { q: "What is the difference between agent orchestration and automation?", a: "Automation executes predefined steps. Agent orchestration also coordinates probabilistic agent work, context, tools, handoffs, observation, evaluation, and human review." },
      { q: "Do I need a multi-agent system?", a: "Usually not at first. Start with one agent and add another only for distinct specialization, independent critique, or a required runtime boundary." },
      { q: "What should an orchestration platform record?", a: "At minimum: the brief, participants, task state, posted evidence and artifacts, run status, review feedback, and final decision." },
    ],
    related: [{ label: "Multi-agent patterns", href: "/blog/multi-agent-workflow-patterns" }, { label: "AI-native teams", href: "/built-for/ai-native-teams" }, { label: "Run observability", href: "/features/agent-run-observability" }],
  },
  {
    slug: "local-vs-cloud-ai-agents",
    title: "Local vs cloud AI agents: how to choose the right runtime",
    metaTitle: "Local vs Cloud AI Agents: Runtime Guide",
    metaDescription: "Compare local and cloud AI agents across setup, data boundaries, tool access, availability, review, and the workflows each runtime fits best.",
    keywords: ["local vs cloud AI agents", "local AI agent", "cloud AI agent", "agent runtime comparison"],
    dek: "The right runtime depends on where the required tools and data live. Local agents fit machine-bound work; cloud agents reduce setup and improve availability for workflows that can use managed context and connectors.",
    directAnswer: "Use a local AI agent when the workflow depends on a repository, credentials, or toolchain that should remain on a controlled machine. Use a cloud agent when the work can run from managed context and approved connectors and the team values zero-install availability. Many teams need both, coordinated through the same review process.",
    published: PUBLISHED,
    updated: PUBLISHED,
    readTime: "8 min read",
    sections: [
      { id: "comparison", title: "Local and cloud agents solve different runtime problems", answer: "Local agents optimize for machine-bound access; cloud agents optimize for managed availability and lower setup.", paragraphs: ["A local coding agent can use a repository and toolchain already present on an engineer's machine. A managed cloud agent can start without waiting for that machine, making it better for research, synthesis, and connected workflows that do not require private local state.", "The runtime choice does not determine who approves the result. Both should post reviewable evidence into a shared workflow and stop short of treating execution as acceptance."], bullets: ["Local: repository and desktop tool access", "Local: depends on machine availability", "Cloud: zero-local-install start", "Cloud: controlled by managed sandbox and connector grants", "Both: need explicit review and evidence"] },
      { id: "data-boundaries", title: "Be precise about data boundaries", answer: "Local repository access does not automatically mean model processing is local.", paragraphs: ["A local bridge can keep repository reads and file operations on the runtime machine while sending selected outputs to a collaboration platform. The underlying AI CLI may still send code or context to its model provider under that provider's terms.", "For cloud agents, teams should identify what context enters the managed runtime and which connector credentials or resources it can use. Describe each boundary separately: machine, orchestration platform, model provider, and connected system."], bullets: ["Where files are read", "What is posted to the workflow room", "What the model provider processes", "Which connector resources are granted", "What evidence remains after the run"] },
      { id: "decision-matrix", title: "A runtime decision matrix", answer: "Choose based on required access, availability, setup cost, and the review model.", paragraphs: ["Local runtimes are a strong fit for code review, repository analysis, and developer toolchains. Cloud runtimes are a strong fit for launch checks, research synthesis, and operational tasks that rely on shared documents or APIs.", "A hybrid workflow can delegate research to a cloud agent and code inspection to a local agent, then bring both outputs to the same human review."], bullets: ["Private repo or local CLI required: local", "Always-on scheduled availability: cloud", "Fast trial without installation: cloud", "Machine-specific credentials or tools: local", "Cross-functional review: shared room for either runtime"] },
      { id: "hybrid-model", title: "Coordinate both without hiding the runtime", answer: "Make runtime identity and data movement visible in the workflow record.", paragraphs: ["Reviewers should know which agent ran locally, which ran in a managed environment, and what evidence each one could access. That context affects both trust and reproducibility.", "Keep handoffs explicit through tasks and posted artifacts. Do not copy all private context between runtimes simply for convenience; transfer the minimum evidence needed for the next step."], bullets: ["Label the runtime and participant", "Use least-privilege context transfer", "Post artifacts needed for review", "Record unavailable evidence and uncertainty", "Keep one human-owned decision"] },
    ],
    sources: [
      { publisher: "Cloudflare", label: "Durable Objects documentation", href: "https://developers.cloudflare.com/durable-objects/" },
      { publisher: "Anthropic", label: "Building effective agents", href: "https://www.anthropic.com/engineering/building-effective-agents" },
      { publisher: "OWASP", label: "Agentic Security Initiative", href: "https://owasp.org/www-project-top-10-for-large-language-model-applications/initiatives/agent_security_initiative/" },
    ],
    faqs: [
      { q: "Are local AI agents always more private?", a: "Not necessarily. Files may be read locally, but the AI CLI can still send context to a model provider. Evaluate the machine, orchestration platform, provider, and connector boundaries separately." },
      { q: "Can local and cloud agents work together?", a: "Yes. Give each a bounded role, transfer only required evidence, and bring both outputs into the same human review process." },
      { q: "Which runtime is easier for a first trial?", a: "A cloud agent usually has lower setup. Choose a local runtime first only when the initial workflow genuinely requires machine-bound tools or repository access." },
    ],
    related: [{ label: "Local bridge feature", href: "/features/local-agent-bridge" }, { label: "Cloud agents", href: "/features/cloud-agents" }, { label: "Bridge runtime answer", href: "/answers/what-is-a-bridge-runtime" }],
  },
  {
    slug: "ai-agent-approval-workflow",
    title: "How to design an AI agent approval workflow",
    metaTitle: "AI Agent Approval Workflow Design Guide",
    metaDescription: "Design AI agent approval workflows with risk tiers, evidence packets, authorized reviewers, destination controls, and clear audit records.",
    keywords: ["AI agent approval workflow", "AI approval gate", "agent authorization", "AI workflow controls"],
    dek: "An approval workflow should control a meaningful transition. It must state what the agent may prepare, what remains unapproved, who can decide, and which external system ultimately enforces the action.",
    directAnswer: "An AI agent approval workflow separates agent preparation from authorized action. The agent produces a proposal and evidence packet, the workflow marks it ready for review, an authorized person approves or rejects it, and the destination system enforces any sensitive action through its own permissions. The approval record should preserve who decided, what evidence they saw, and what changed afterward.",
    published: PUBLISHED,
    updated: PUBLISHED,
    readTime: "9 min read",
    sections: [
      { id: "approval-object", title: "Define exactly what is being approved", answer: "Approve a specific claim, artifact, change, or external action rather than a vague agent run.", paragraphs: ["A reviewer cannot evaluate 'the agent completed successfully.' They can evaluate a launch recommendation, a code change, a customer-facing message, or a request to update a connected system.", "Write the approval object into the brief and task. This prevents a completion signal from silently expanding into authorization."], bullets: ["The proposed output", "The affected users or systems", "The permitted next action", "The expiration or scope of approval", "What remains prohibited"] },
      { id: "risk-tiers", title: "Use risk tiers to avoid approval fatigue", answer: "Reserve high-attention approval for impactful, uncertain, or irreversible transitions.", paragraphs: ["Classify, summarize, and draft can often proceed with sampling and exception review. Publishing, sending, changing production, granting access, or spending money needs stronger authorization.", "Risk tiers should consider both impact and reversibility. A small but irreversible disclosure may deserve more review than a larger internal draft."], bullets: ["Tier 1: internal preparation", "Tier 2: internal publication or planning decision", "Tier 3: customer-facing or production action", "Tier 4: regulated, financial, access, or irreversible action"] },
      { id: "evidence-packet", title: "Require an evidence packet before review", answer: "The reviewer needs sources, uncertainty, diffs, tests, and affected scope appropriate to the task.", paragraphs: ["The approval interface should summarize the decision without hiding the underlying evidence. For code, show affected paths and test results. For research, show source dates and contradictions. For outreach, show the basis for targeting and the exact message.", "A missing-evidence state should stop or defer approval instead of encouraging the agent to fill gaps with confident language."], bullets: ["Recommendation and alternatives", "Source links or artifacts", "Known uncertainty", "Validation results", "Rollback or correction path"] },
      { id: "enforcement-and-record", title: "Pair workflow approval with destination-system enforcement", answer: "The workflow coordinates review; the external system should still enforce who can perform the action.", paragraphs: ["A review state inside an orchestration platform is valuable evidence, but it should not become the only permission boundary for production, financial, or customer-facing operations. Keep repository protection, CRM permissions, deployment controls, and identity policies active.", "After the decision, record the reviewer, outcome, feedback, and resulting action. This creates a useful audit trail and improves the next workflow run."], bullets: ["Authorized reviewer identity", "Approval or rejection timestamp", "Evidence version reviewed", "External action reference", "Post-action verification"] },
    ],
    sources: [
      { publisher: "NIST", label: "AI RMF Core", href: "https://airc.nist.gov/airmf-resources/airmf/5-sec-core/" },
      { publisher: "Anthropic", label: "Building and evaluating trustworthy agents", href: "https://www.anthropic.com/research/trustworthy-agents" },
      { publisher: "OWASP", label: "Agentic Security Initiative", href: "https://owasp.org/www-project-top-10-for-large-language-model-applications/initiatives/agent_security_initiative/" },
    ],
    faqs: [
      { q: "Is an in-review task a security control?", a: "It is a workflow signal and record. Sensitive actions should also be enforced by destination-system permissions and authorized identities." },
      { q: "Who should approve AI agent work?", a: "The person with domain context and authority for the affected decision, not simply whoever is available to click approve." },
      { q: "How do you avoid approval fatigue?", a: "Automate low-impact preparation, surface exceptions, and reserve focused approval for consequential, uncertain, or irreversible transitions." },
    ],
    related: [{ label: "Human review feature", href: "/features/human-review" }, { label: "Approval gates answer", href: "/answers/how-do-ai-agent-approval-gates-work" }, { label: "Security", href: "/security" }],
  },
  {
    slug: "ai-agent-observability",
    title: "AI agent observability: what teams need to see",
    metaTitle: "AI Agent Observability: Practical Guide",
    metaDescription: "Understand AI agent observability across run state, tool use, evidence, outputs, evaluation, review, and the workflow decisions teams must retain.",
    keywords: ["AI agent observability", "agent monitoring", "AI agent tracing", "agent evaluation"],
    dek: "Agent observability connects execution telemetry to the workflow record. Teams need enough evidence to diagnose failures and review outcomes without pretending they can inspect hidden model reasoning.",
    directAnswer: "AI agent observability is the ability to inspect an agent's execution state, inputs and tool interactions where available, posted outputs and artifacts, errors, evaluation results, and human review outcome. It should help a team answer what ran, what evidence was used, what failed, and whether the result was accepted. It is not the same as exposing private chain-of-thought.",
    published: PUBLISHED,
    updated: PUBLISHED,
    readTime: "9 min read",
    sections: [
      { id: "layers", title: "Observe both the run and the workflow", answer: "Technical traces explain execution; workflow context explains whether the work mattered and was accepted.", paragraphs: ["Runtime telemetry can show starts, stops, tool calls, errors, and latency. The workflow record adds the brief, expected proof, reviewer feedback, tasks, and final decision.", "Without technical telemetry, failures are difficult to diagnose. Without workflow context, a successful trace can still represent the wrong task or an unapproved result."], bullets: ["Runtime and agent identity", "Start, stop, waiting, and error state", "Tool interactions and artifacts where available", "Posted evidence and uncertainty", "Evaluation and human review outcome"] },
      { id: "truthful-visibility", title: "Do not confuse observability with chain-of-thought", answer: "Observe actions, evidence, outputs, and evaluations rather than demanding hidden reasoning.", paragraphs: ["Useful observability does not require a model to reveal private internal reasoning. Teams can inspect the sources selected, tools called, files changed, tests run, outputs posted, and critiques produced.", "This action-and-evidence record is more operationally useful because it can be validated against the real environment."], bullets: ["Prefer source citations over narrative confidence", "Prefer diffs and tests over claims of correctness", "Prefer explicit uncertainty over invented certainty", "Record reviewer feedback and revision"] },
      { id: "evals", title: "Connect traces to task-specific evaluations", answer: "A trace shows what happened; an evaluation tests whether the output met the workflow's requirements.", paragraphs: ["Anthropic recommends using evaluations to make agent behavior measurable. Build a small set of representative cases and score the qualities that matter: evidence accuracy, completeness, policy compliance, or code correctness.", "Use production corrections and rejected outputs to improve the evaluation set. That closes the loop between observation and workflow quality."], bullets: ["Representative tasks", "Clear scoring rubric", "Failure categories", "Human-reviewed examples", "Regression checks after workflow changes"] },
      { id: "operating-metrics", title: "Track operating metrics that support decisions", answer: "Measure review readiness, failure recovery, corrections, and reusable outcomes rather than token volume alone.", paragraphs: ["Latency and cost matter, but they do not prove value. Track time to a review-ready result, the rate of missing evidence, how often humans reject or materially revise output, and whether the next run can reuse the prior record.", "These metrics reveal whether orchestration is reducing work or merely creating more output to inspect."], bullets: ["Time to review-ready artifact", "Tool or runtime failure rate", "Evidence completeness", "Material correction rate", "Time to recover or hand off", "Reuse in later workflows"] },
    ],
    sources: [
      { publisher: "OpenAI", label: "New tools for building agents", href: "https://openai.com/index/new-tools-for-building-agents/" },
      { publisher: "Anthropic", label: "Demystifying evals for AI agents", href: "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents" },
      { publisher: "NIST", label: "AI Risk Management Framework", href: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10" },
    ],
    faqs: [
      { q: "Is AI agent observability the same as logging?", a: "Logging is one layer. Observability also connects traces, artifacts, evaluations, workflow state, and human review so teams can interpret and improve behavior." },
      { q: "Should an agent reveal chain-of-thought?", a: "No. Teams can evaluate actions, evidence, artifacts, test results, and outputs without requesting hidden private reasoning." },
      { q: "What is the most important agent metric?", a: "For many teams, time to a review-ready, evidence-backed outcome is more useful than message or token volume." },
    ],
    related: [{ label: "Run observability feature", href: "/features/agent-run-observability" }, { label: "How teams review output", href: "/answers/how-do-teams-review-ai-agent-output" }, { label: "Human-in-the-loop guide", href: "/blog/human-in-the-loop-ai-workflows" }],
  },
  {
    slug: "multi-agent-workflow-patterns",
    title: "Seven multi-agent workflow patterns that teams can review",
    metaTitle: "7 Multi-Agent Workflow Patterns for Teams",
    metaDescription: "Use seven practical multi-agent patterns for routing, parallel research, critique, handoffs, local-cloud collaboration, and human review.",
    keywords: ["multi agent workflow", "multi agent patterns", "agent handoff", "agent collaboration"],
    dek: "Multi-agent systems are useful when roles are genuinely distinct. These seven patterns keep task ownership, context transfer, evidence, and review visible instead of simulating an organization chart.",
    directAnswer: "The most useful multi-agent patterns are router-specialist, parallel research, researcher-critic, planner-executor, local-cloud split, exception escalation, and synthesis-review. Each pattern needs explicit task ownership, minimal context transfer, observable outputs, and a human owner for the consequential result.",
    published: PUBLISHED,
    updated: PUBLISHED,
    readTime: "10 min read",
    sections: [
      { id: "routing-patterns", title: "1-2. Router-specialist and planner-executor", answer: "Use routing when tasks need different expertise; use planning when execution benefits from an explicit, reviewable task breakdown.", paragraphs: ["A router classifies the request and assigns it to one specialist. A planner decomposes a larger objective into tasks that executors claim and update. Keep the routing criteria and plan visible so humans can correct a bad decomposition early.", "Do not let the router become an opaque gate. Record why a task was assigned and make it easy to reassign."], bullets: ["Router-specialist: one clear owner per classified task", "Planner-executor: review the plan before expensive execution", "Use task states for handoffs", "Escalate ambiguous routing to a person"] },
      { id: "research-patterns", title: "3-4. Parallel research and researcher-critic", answer: "Parallelize independent evidence domains, then use a critic to challenge synthesis rather than repeat the same search.", paragraphs: ["Parallel research works when agents receive non-overlapping scopes and a common citation standard. A researcher-critic pattern adds independent pressure testing: the critic looks for unsupported claims, missing counterevidence, and stale sources.", "The synthesis should preserve disagreements instead of forcing false consensus."], bullets: ["Partition evidence by domain or source type", "Use shared freshness and citation rules", "Give the critic access to the brief and evidence", "Record unresolved contradictions"] },
      { id: "runtime-patterns", title: "5-6. Local-cloud split and exception escalation", answer: "Assign machine-bound work locally, managed research in the cloud, and uncertain exceptions to a human.", paragraphs: ["A cloud agent can gather public or connected evidence while a local runtime inspects a repository. Transfer only the findings needed for synthesis; do not move private context between runtimes by default.", "Exception escalation is a powerful pattern: the agent handles routine cases but creates a review task when confidence is low, evidence conflicts, or a prohibited action would be required."], bullets: ["Label each runtime and accessible context", "Transfer minimum necessary evidence", "Define confidence or rule-based escalation", "Keep external actions human-owned"] },
      { id: "synthesis-pattern", title: "7. Synthesis-review", answer: "A synthesizer combines specialist outputs, then a human reviews the decision packet against the original brief.", paragraphs: ["The synthesizer should not erase source attribution. It should identify agreements, contradictions, missing work, and the recommendation being proposed.", "The human reviewer evaluates whether the final packet answers the original question and whether any additional evidence or authorized action is needed."], bullets: ["Preserve specialist attribution", "Separate facts, inference, and recommendation", "Surface incomplete tasks", "Request one explicit decision", "Record approval or revision"] },
    ],
    sources: [
      { publisher: "Anthropic", label: "Building effective agents", href: "https://www.anthropic.com/engineering/building-effective-agents" },
      { publisher: "OpenAI", label: "The next evolution of the Agents SDK", href: "https://openai.com/index/the-next-evolution-of-the-agents-sdk/" },
      { publisher: "OpenAI", label: "New tools for building agents", href: "https://openai.com/index/new-tools-for-building-agents/" },
    ],
    faqs: [
      { q: "How many agents should a workflow use?", a: "Use the fewest needed. One agent is often enough; add specialists only for distinct evidence, independent critique, or runtime requirements." },
      { q: "What is the biggest multi-agent failure mode?", a: "Unclear ownership and hidden context loss. Explicit tasks, attributed artifacts, and reviewable handoffs reduce both." },
      { q: "Can local and cloud agents be in one pattern?", a: "Yes. A local-cloud split is useful when repository work must stay machine-bound while research or coordination can run in managed infrastructure." },
    ],
    related: [{ label: "Agent orchestration guide", href: "/blog/ai-agent-orchestration-guide" }, { label: "Tasks and handoffs", href: "/features/tasks-and-handoffs" }, { label: "Can Claude and Codex work together?", href: "/answers/can-claude-code-and-codex-work-together" }],
  },
  {
    slug: "ai-agent-workflow-examples-product-teams",
    title: "Eight AI agent workflow examples for product teams",
    metaTitle: "8 AI Agent Workflow Examples for Product Teams",
    metaDescription: "Explore eight reviewable AI agent workflows for product discovery, launch readiness, customer risk, research, release notes, and decision records.",
    keywords: ["AI agent workflow examples", "AI workflows for product managers", "product team AI", "product agent use cases"],
    dek: "The best product workflows delegate evidence preparation while preserving customer judgment, prioritization, and launch decisions for the team.",
    directAnswer: "Useful AI agent workflows for product teams include research synthesis, launch readiness, customer-risk review, feedback classification, competitive change monitoring, release-note preparation, experiment review, and decision-record maintenance. Each should produce inspectable evidence and stop at a human-owned product decision.",
    published: PUBLISHED,
    updated: PUBLISHED,
    readTime: "10 min read",
    sections: [
      { id: "discovery", title: "1-2. Research synthesis and feedback classification", answer: "Use agents to structure evidence, not to decide what customers need.", paragraphs: ["For research synthesis, give agents a bounded question, source standard, and date cutoff. Require citations, contradictions, and open questions. For feedback classification, define a stable taxonomy and keep representative raw evidence available for review.", "The product owner decides which themes matter and whether the evidence is sufficient to change direction."], bullets: ["Output: source-linked research brief", "Output: classified themes with examples", "Review: evidence quality and missing segments", "Decision: product priority remains human-owned"] },
      { id: "launch", title: "3-4. Launch readiness and release-note preparation", answer: "Agents can collect readiness evidence and draft communication while people approve launch risk and claims.", paragraphs: ["A launch-readiness workflow checks scope, dependencies, tests, known customer impact, and unresolved tasks. A release-note workflow turns accepted changes into a draft but links each claim back to shipped evidence.", "Neither workflow should treat a draft as authorization to release or publish."], bullets: ["Output: blockers and evidence gaps", "Output: source-linked release-note draft", "Review: engineering, product, and GTM owners", "Decision: go/no-go and public claims"] },
      { id: "customer-market", title: "5-6. Customer-risk review and competitive change monitoring", answer: "Agents can surface patterns and changes, but teams must verify current sources and choose the response.", paragraphs: ["Customer-risk review combines support, product, and account signals into confidence-labeled themes. Competitive monitoring compares dated first-party sources and highlights what changed rather than generating a generic battlecard.", "Both need freshness controls because stale evidence can be more damaging than missing evidence."], bullets: ["Output: prioritized risks with affected evidence", "Output: dated competitor change log", "Review: confidence, source freshness, and impact", "Decision: account or positioning action"] },
      { id: "learning-memory", title: "7-8. Experiment review and decision-record maintenance", answer: "Use agents to prepare the learning record, then let the team interpret causality and tradeoffs.", paragraphs: ["An experiment-review agent can gather the hypothesis, metric definitions, results, segments, and instrumentation caveats. A decision-record agent can summarize accepted evidence, alternatives, and follow-up tasks from the workflow room.", "The team owns whether an experiment supports a conclusion and whether the decision should change."], bullets: ["Output: experiment evidence packet", "Output: searchable decision record", "Review: data quality and causal limits", "Decision: ship, iterate, stop, or investigate"] },
    ],
    sources: [
      { publisher: "NIST", label: "AI Risk Management Framework", href: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10" },
      { publisher: "Anthropic", label: "Building effective agents", href: "https://www.anthropic.com/engineering/building-effective-agents" },
      { publisher: "OpenAI", label: "A practical guide to building AI agents", href: "https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/" },
    ],
    faqs: [
      { q: "What product workflow should I automate first?", a: "Start with a bounded, recurring process with available evidence and a clear owner. Launch readiness or research synthesis are usually easier to evaluate than broad product strategy." },
      { q: "Should an AI agent prioritize the roadmap?", a: "It can prepare evidence and alternatives, but product prioritization involves customer judgment and tradeoffs that should remain human-owned." },
      { q: "How do teams keep these workflows from creating more noise?", a: "Require a defined artifact, evidence standard, review owner, and stop condition. Measure time to reviewed value rather than output volume." },
    ],
    related: [{ label: "For product teams", href: "/built-for/product-teams" }, { label: "Launch readiness", href: "/workflows/launch-readiness" }, { label: "Research synthesis", href: "/workflows/research-synthesis" }],
  },
  ...EXPANDED_BLOG_ARTICLES,
  ...ROUND_TWO_BLOG_ARTICLES,
];

export const ANSWER_PAGES: AnswerPage[] = [
  {
    slug: "what-is-an-ai-workflow-room",
    question: "What is an AI workflow room?",
    metaTitle: "What Is an AI Workflow Room?",
    metaDescription: "An AI workflow room keeps the brief, agents, tasks, evidence, human review, and final decision together for one repeatable process.",
    keywords: ["what is an AI workflow room", "AI workflow room", "agent workspace"],
    shortAnswer: "An AI workflow room is a shared space for one repeatable agent-assisted process. It contains the brief, human and agent participants, task state, posted evidence and artifacts, review feedback, and final decision. Unlike a general chat channel, it is organized around a bounded outcome and an accountable owner.",
    sections: [
      { id: "contents", title: "What belongs in a workflow room?", answer: "Everything required to understand and review one process should remain attached to the room.", paragraphs: ["That includes the objective, constraints, evidence, agent updates, tasks, artifacts, uncertainty, reviewer feedback, and accepted outcome. A later teammate should not need several private chats to reconstruct what happened."], bullets: ["Brief and acceptance criteria", "Human and agent participants", "Tasks and run state", "Evidence and artifacts", "Review and final decision"] },
      { id: "difference", title: "How is it different from a chat channel?", answer: "A chat channel organizes messages; a workflow room organizes work toward a reviewed result.", paragraphs: ["General chat can host an AI bot, but the process model is usually implicit. A workflow room makes ownership, task state, evidence, and review part of the primary surface."], bullets: ["Bounded process", "Explicit deliverable", "Visible handoffs", "Human-owned approval", "Reusable operating memory"] },
      { id: "example", title: "What is a simple example?", answer: "A launch-readiness room can collect scope and evidence, assign checks, surface blockers, and record the go or no-go decision.", paragraphs: ["The agent prepares a structured assessment, but the launch owner reviews the evidence and makes the decision. The next release can reuse the room pattern and compare what changed."] },
    ],
    faqs: [{ q: "Can a workflow room include multiple agents?", a: "Yes, but start with one. Add specialists only for distinct work or independent review." }, { q: "Is a workflow room only for engineering?", a: "No. Product, research, customer-risk, GTM, and operational workflows can use the same model." }],
    related: [{ label: "Workflow rooms feature", href: "/features/workflow-rooms" }, { label: "Agent workflow guide", href: "/blog/what-is-an-agent-workflow" }, { label: "Workflow templates", href: "/workflows" }],
  },
  {
    slug: "how-do-ai-agent-approval-gates-work",
    question: "How do AI agent approval gates work?",
    metaTitle: "How Do AI Agent Approval Gates Work?",
    metaDescription: "AI agent approval gates separate a proposed output from an authorized decision and preserve the evidence, reviewer, and outcome.",
    keywords: ["how AI approval gates work", "AI agent approval gate", "human approval AI"],
    shortAnswer: "An AI agent approval gate marks a transition where agent work is ready for a qualified person to evaluate but is not yet accepted or authorized. The reviewer checks the proposal, evidence, uncertainty, and affected systems, then approves, rejects, or requests changes. Sensitive external actions should still be enforced by the destination system's permissions.",
    sections: [
      { id: "steps", title: "What are the steps in an approval gate?", answer: "Define the approval object, prepare evidence, move work to review, decide, and record the result.", paragraphs: ["The gate should apply to a specific artifact or action rather than a generic run-complete signal. The reviewer must be able to change what happens next."], bullets: ["Name the decision owner", "State acceptance criteria", "Attach evidence and uncertainty", "Approve, reject, or revise", "Record the resulting action"] },
      { id: "limits", title: "What does an approval gate not guarantee?", answer: "A visible review state does not automatically enforce every external permission or prove the output is correct.", paragraphs: ["Repository protection, deployment controls, CRM permissions, and other destination-system safeguards should remain active. Review quality also depends on reviewer expertise and attention."] },
      { id: "placement", title: "Where should approval gates be placed?", answer: "Place them before consequential, uncertain, customer-facing, financial, access, or hard-to-reverse actions.", paragraphs: ["Routine low-impact preparation can use sampling or exception review. Too many gates create approval fatigue; too few remove meaningful control."] },
    ],
    faqs: [{ q: "Does every agent task need approval?", a: "No. Match review to impact, uncertainty, and reversibility." }, { q: "Can Raltic show work as in review?", a: "Yes. Raltic tasks include an in-review state and keep the relevant room evidence visible." }],
    related: [{ label: "Human review feature", href: "/features/human-review" }, { label: "Approval workflow guide", href: "/blog/ai-agent-approval-workflow" }, { label: "Security", href: "/security" }],
  },
  {
    slug: "can-claude-code-and-codex-work-together",
    question: "Can Claude Code and Codex work together?",
    metaTitle: "Can Claude Code and Codex Work Together?",
    metaDescription: "Claude Code and OpenAI Codex can participate in the same team workflow when roles, context, tasks, and review are explicitly coordinated.",
    keywords: ["Claude Code and Codex together", "Claude Codex workflow", "multiple coding agents"],
    shortAnswer: "Yes. Claude Code and OpenAI Codex can work in the same broader workflow when an orchestration layer gives each runtime a clear task, limits the context transferred between them, preserves attributed outputs, and brings both results to one human review. Raltic verifies both as bridge runtimes and can place them in the same workspace.",
    sections: [
      { id: "roles", title: "How should their roles be divided?", answer: "Assign distinct work rather than asking both agents to produce the same broad answer.", paragraphs: ["One runtime might inspect implementation and tests while another critiques risks or checks a different subsystem. Independent duplicate review can also be useful when disagreement is intentional."], bullets: ["Implementation and critique", "Repository inspection and research", "Primary review and independent check", "Different bounded components"] },
      { id: "context", title: "How should context move between runtimes?", answer: "Transfer the minimum evidence needed through explicit messages, artifacts, and tasks.", paragraphs: ["Avoid copying entire private sessions. Preserve source attribution and identify which runtime had access to which files or tools so reviewers can interpret the result."] },
      { id: "review", title: "Who owns the final decision?", answer: "A human reviewer remains responsible for accepting code findings, changes, or release decisions.", paragraphs: ["Two agents agreeing does not make the result correct. Review diffs, tests, source evidence, and unresolved disagreement before acceptance."] },
    ],
    faqs: [{ q: "Does Raltic pay for Claude or Codex usage?", a: "No. Bridge-runtime subscriptions or keys stay with the user, who pays each provider directly." }, { q: "Should both agents edit the same files?", a: "Usually not concurrently. Divide ownership or use one as a reviewer to reduce conflict and unclear attribution." }],
    related: [{ label: "Runtimes", href: "/runtimes" }, { label: "Multi-agent patterns", href: "/blog/multi-agent-workflow-patterns" }, { label: "Local bridge", href: "/features/local-agent-bridge" }],
  },
  {
    slug: "does-raltic-upload-source-code",
    question: "Does Raltic upload source code?",
    metaTitle: "Does Raltic Upload Source Code?",
    metaDescription: "For bridge-hosted agents, repositories are read on the runtime machine; Raltic receives only content deliberately posted to workflow rooms.",
    keywords: ["does Raltic upload code", "Raltic source code privacy", "local AI code review privacy"],
    shortAnswer: "Raltic does not automatically mirror or upload a repository for bridge-hosted agents. Claude Code or Codex reads the repository on the machine running the local runtime. Raltic receives messages, artifacts, and run status deliberately posted into a workflow room. The AI CLI may separately send code or context to its model provider under that provider's terms.",
    sections: [
      { id: "raltic-receives", title: "What can Raltic receive?", answer: "Raltic receives content a user or agent intentionally posts into the product.", paragraphs: ["That can include messages, code excerpts, files, artifacts, task updates, and run status. Teams should review what is posted and avoid including secrets or unnecessary sensitive data."], bullets: ["Room messages", "Posted files and artifacts", "Task and run status", "Connector data within granted scope"] },
      { id: "local-runtime", title: "What stays on the local runtime machine?", answer: "Repository reads and local tool operations happen on the machine running the bridge runtime.", paragraphs: ["The runtime can inspect files and use its installed toolchain without Raltic automatically copying the repository. Availability depends on that machine and its authenticated runtime."] },
      { id: "provider", title: "What can the model provider receive?", answer: "The underlying AI CLI may send context to Anthropic, OpenAI, or another configured provider.", paragraphs: ["That data path is separate from what Raltic receives. Teams should evaluate provider settings, plans, privacy terms, and retention controls for the CLI they use."] },
    ],
    faqs: [{ q: "Can a user intentionally post code to Raltic?", a: "Yes. A user or agent can deliberately post an excerpt or file for team review, so sensitive-content practices still matter." }, { q: "Are cloud agents the same as bridge agents?", a: "No. Cloud agents run in managed containers; bridge agents run on a user's machine and connect through the local bridge." }],
    related: [{ label: "Security disclosures", href: "/security" }, { label: "Local bridge feature", href: "/features/local-agent-bridge" }, { label: "Local vs cloud agents", href: "/blog/local-vs-cloud-ai-agents" }],
  },
  {
    slug: "what-is-a-bridge-runtime",
    question: "What is a bridge runtime?",
    metaTitle: "What Is a Bridge Runtime for AI Agents?",
    metaDescription: "A bridge runtime connects a local AI CLI such as Claude Code or Codex to shared workflow rooms while execution stays on the local machine.",
    keywords: ["what is a bridge runtime", "AI agent bridge", "local agent runtime"],
    shortAnswer: "A bridge runtime is a local AI agent process connected to a shared orchestration platform through an authenticated daemon. The local runtime receives room work, uses tools and files available on its machine, and posts selected messages, artifacts, and status back to the team workspace. In Raltic, Claude Code and OpenAI Codex are verified bridge runtimes.",
    sections: [
      { id: "components", title: "What are the components?", answer: "A bridge includes the daemon, runtime adapter, authenticated API connection, and the local AI CLI.", paragraphs: ["The daemon maintains room connections and dispatches inbound work to the selected runtime. The runtime then posts progress and results back through the authenticated Raltic CLI or API surface."], bullets: ["Local bridge daemon", "Supported runtime adapter", "Authenticated workspace connection", "Local AI CLI and provider access"] },
      { id: "benefits", title: "Why use a bridge runtime?", answer: "Use it when an agent needs a local repository, developer toolchain, or machine-specific environment.", paragraphs: ["The bridge gives the wider team visibility into selected work while leaving machine-bound execution on the controlled host."] },
      { id: "limits", title: "What are the operational limits?", answer: "The machine must be online, the runtime authenticated, and the team must understand both Raltic and model-provider data paths.", paragraphs: ["A bridge improves coordination but does not make the underlying model local or eliminate the need to secure posted artifacts."] },
    ],
    faqs: [{ q: "Which Raltic bridge runtimes are verified?", a: "Claude Code and OpenAI Codex. OpenClaw and Hermes remain experimental." }, { q: "Does a bridge runtime require cloud execution?", a: "No. The agent process runs on the local host, while communication and team coordination use Raltic's cloud service." }],
    related: [{ label: "Local bridge feature", href: "/features/local-agent-bridge" }, { label: "Runtime compatibility", href: "/runtimes" }, { label: "Source code answer", href: "/answers/does-raltic-upload-source-code" }],
  },
  {
    slug: "how-do-teams-review-ai-agent-output",
    question: "How should teams review AI agent output?",
    metaTitle: "How Should Teams Review AI Agent Output?",
    metaDescription: "Review AI agent output by checking the brief, evidence, uncertainty, validation results, affected scope, and the human-owned decision.",
    keywords: ["review AI agent output", "AI output review checklist", "agent quality review"],
    shortAnswer: "Teams should review AI agent output against the original brief and acceptance criteria, inspect supporting and conflicting evidence, validate high-impact claims or changes in the real environment, check uncertainty and affected scope, and record whether the output was approved, rejected, or revised. A completed run is not the same as accepted work.",
    sections: [
      { id: "checklist", title: "What should every review check?", answer: "Check task fit, evidence, correctness, uncertainty, impact, and ownership.", paragraphs: ["The exact validation depends on the domain, but the reviewer should always be able to connect the result back to the requested outcome and understand what remains unproven."], bullets: ["Does it answer the brief?", "Are important claims supported?", "What evidence conflicts or is missing?", "Were tests or validations run?", "Who owns the next action?"] },
      { id: "domain", title: "How does review differ by workflow?", answer: "Code needs diffs and tests; research needs sources and freshness; customer-facing work needs claim and authorization review.", paragraphs: ["Use a domain-specific evidence packet rather than a generic confidence score. High-impact work should be verified in the system where the action will occur."] },
      { id: "record", title: "What should the team retain?", answer: "Retain the output version reviewed, evidence, feedback, reviewer, decision, and resulting task or action.", paragraphs: ["This record supports audits, onboarding, regression analysis, and better future briefs."] },
    ],
    faqs: [{ q: "Is model confidence enough for review?", a: "No. Confidence language is not a substitute for source evidence, tests, or domain validation." }, { q: "Should reviewers inspect every raw log?", a: "Not normally. Give reviewers a concise evidence packet with access to deeper artifacts when needed." }],
    related: [{ label: "Agent observability", href: "/blog/ai-agent-observability" }, { label: "Run observability feature", href: "/features/agent-run-observability" }, { label: "Human review", href: "/features/human-review" }],
  },
  {
    slug: "what-is-human-in-the-loop-agent-orchestration",
    question: "What is human-in-the-loop agent orchestration?",
    metaTitle: "What Is Human-in-the-Loop Agent Orchestration?",
    metaDescription: "Human-in-the-loop agent orchestration coordinates AI execution and handoffs while people retain meaningful control of consequential decisions.",
    keywords: ["human in the loop agent orchestration", "human AI orchestration", "agent oversight"],
    shortAnswer: "Human-in-the-loop agent orchestration coordinates agents, tools, tasks, and handoffs while placing qualified people at meaningful decision points. Agents perform bounded preparation and propose results; humans inspect evidence, resolve ambiguity, authorize consequential transitions, and remain able to stop or revise the workflow.",
    sections: [
      { id: "orchestration", title: "What does the orchestration layer do?", answer: "It routes tasks, controls context and tools, records state, and brings agent work to the right reviewer.", paragraphs: ["The layer should make role, runtime, task ownership, and review state visible rather than hiding the process inside prompt chains."] },
      { id: "human-role", title: "What does the human do?", answer: "The human defines goals, evaluates evidence, handles exceptions, and owns high-impact decisions.", paragraphs: ["Meaningful control requires authority and context. A ceremonial approval click after an opaque run is not sufficient."], bullets: ["Define acceptance criteria", "Review exceptions and uncertainty", "Approve or reject consequential output", "Improve the workflow from corrections"] },
      { id: "benefit", title: "Why combine orchestration and human review?", answer: "It allows agents to move faster on preparation while keeping accountability and recovery paths explicit.", paragraphs: ["The team gains parallelism without treating autonomy as an all-or-nothing choice."] },
    ],
    faqs: [{ q: "Is human-in-the-loop slower than full automation?", a: "It adds review where needed, but can reduce costly corrections. Use risk tiers so low-impact work does not require unnecessary approval." }, { q: "Can multiple agents share one review point?", a: "Yes. A synthesizer can combine attributed specialist outputs into one evidence packet for a human decision." }],
    related: [{ label: "Human-in-the-loop guide", href: "/blog/human-in-the-loop-ai-workflows" }, { label: "Orchestration guide", href: "/blog/ai-agent-orchestration-guide" }, { label: "Human review feature", href: "/features/human-review" }],
  },
  {
    slug: "do-ai-agents-need-a-shared-workspace",
    question: "Do AI agents need a shared workspace?",
    metaTitle: "Do AI Agents Need a Shared Workspace?",
    metaDescription: "A shared agent workspace is useful when teams need coordinated context, task ownership, review, evidence, and reusable decisions across runtimes.",
    keywords: ["AI agent shared workspace", "do AI agents need shared workspace", "multi agent workspace"],
    shortAnswer: "AI agents need a shared workspace when several people or runtimes must coordinate around the same recurring work. The workspace should preserve a common brief, attributed outputs, tasks, artifacts, review state, and the final decision. A solo, one-off task may not need one; team workflows with handoffs and accountability usually do.",
    sections: [
      { id: "when-needed", title: "When is a shared workspace necessary?", answer: "Use one when context, ownership, or review crosses people, agents, sessions, or tools.", paragraphs: ["A private AI session is enough for disposable brainstorming. It becomes a coordination problem when another person must inspect the evidence, continue the work, or own the result."], bullets: ["Multiple agent runtimes", "Cross-functional review", "Recurring workflows", "Shared artifacts and tasks", "Decisions that need an audit trail"] },
      { id: "requirements", title: "What should the workspace contain?", answer: "It should make the workflow legible without requiring access to every private runtime session.", paragraphs: ["Preserve the bounded brief, posted evidence, attributed participants, tasks, run state, review feedback, and accepted output."] },
      { id: "limits", title: "What should not be shared by default?", answer: "Do not move every private file, secret, or model context into shared storage merely for convenience.", paragraphs: ["Use least-privilege connector grants and transfer only the evidence needed by the next participant or reviewer."] },
    ],
    faqs: [{ q: "Can a solo founder benefit from a shared workspace?", a: "Yes, when several agents or recurring workflows need reusable history. It reduces the need to reconstruct prior decisions." }, { q: "Does shared mean every agent sees everything?", a: "No. Shared workflow context should still be combined with per-agent grants and bounded access." }],
    related: [{ label: "Workflow rooms", href: "/features/workflow-rooms" }, { label: "For AI-native teams", href: "/built-for/ai-native-teams" }, { label: "What is a workflow room?", href: "/answers/what-is-an-ai-workflow-room" }],
  },
  ...EXPANDED_ANSWER_PAGES,
  ...ROUND_TWO_ANSWER_PAGES,
];

export function getBlogArticle(slug: string | null | undefined): BlogArticle | null {
  return BLOG_ARTICLES.find((article) => article.slug === slug) ?? null;
}

export function getAnswerPage(slug: string | null | undefined): AnswerPage | null {
  return ANSWER_PAGES.find((answer) => answer.slug === slug) ?? null;
}
